/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dto.Mesa;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logica.LogicaNegocio;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculaValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author sergio
 */
public class AltaMesa extends javax.swing.JDialog {

    private GestionMesas gestionMesas;
    private LogicaNegocio logicaNegocio;
    private Mesa mesaModificar = null;

    /**
     * Creates new form AltaMesa
     */
    // Constructor Alta
    public AltaMesa(java.awt.Dialog parent, boolean modal, LogicaNegocio logicaNegocio) {
        super(parent, modal);
        gestionMesas = (GestionMesas) parent;
        this.logicaNegocio = logicaNegocio;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("ALTA MESA");

        jButtonAltaMesaAceptar.setEnabled(false);
        ValidationGroup group = validationPanelAltaMesa.getValidationGroup();
        group.add(jTextFieldIdentificador, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);
        // MSG_MAY_NOT_BE_EMPTY, ERR_NOT_INTEGER en Bundle_es.properties
        group.add(jTextFieldLocalizacion, StringValidators.REQUIRE_NON_EMPTY_STRING, new MayusculaValidator());
        // MSG_MAYUSCULA en Bundle_es.properties
        group.add(jTextFieldCapacidad, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);

        validationPanelAltaMesa.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanelAltaMesa.getProblem() == null) {
                    jButtonAltaMesaAceptar.setEnabled(true);
                } else {
                    jButtonAltaMesaAceptar.setEnabled(false);
                }
            }
        });
    }

    // Constructor Modificar
    public AltaMesa(java.awt.Dialog parent, boolean modal, LogicaNegocio logicaNegocio, Mesa mesaModificar) {
        super(parent, modal);
        gestionMesas = (GestionMesas) parent;
        this.logicaNegocio = logicaNegocio;
        this.mesaModificar = mesaModificar;
        initComponents();
        setTitle("MODIFICACIÓN MESA");

        jTextFieldIdentificador.setText(Integer.toString(mesaModificar.getIdMesa()));
        jTextFieldIdentificador.setEnabled(false);
        jTextFieldLocalizacion.setText(mesaModificar.getLocalizacion());
        jTextFieldCapacidad.setText(Integer.toString(mesaModificar.getCapacidad()));

        jButtonAltaMesaAceptar.setEnabled(false);
        ValidationGroup group = validationPanelAltaMesa.getValidationGroup();
        //group.add(jTextFieldIdentificador, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);
        // MSG_MAY_NOT_BE_EMPTY, ERR_NOT_INTEGER en Bundle_es.properties
        group.add(jTextFieldLocalizacion, StringValidators.REQUIRE_NON_EMPTY_STRING, new MayusculaValidator());
        // MSG_MAYUSCULA en Bundle_es.properties
        group.add(jTextFieldCapacidad, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER);

        validationPanelAltaMesa.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (validationPanelAltaMesa.getProblem() == null) {
                    jButtonAltaMesaAceptar.setEnabled(true);
                } else {
                    jButtonAltaMesaAceptar.setEnabled(false);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaMesa = new javax.swing.JLabel();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabelLocalizacion = new javax.swing.JLabel();
        jLabelCapacidad = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldLocalizacion = new javax.swing.JTextField();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jButtonAltaMesaAceptar = new javax.swing.JButton();
        validationPanelAltaMesa = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelAltaMesa.setText("ALTA MESA");

        jLabelIdentificador.setText("Identificador");

        jLabelLocalizacion.setText("Localización");

        jLabelCapacidad.setText("Capacidad");

        jTextFieldIdentificador.setName("Identificador"); // NOI18N

        jTextFieldLocalizacion.setName("Localización"); // NOI18N

        jTextFieldCapacidad.setName("Capacidad"); // NOI18N

        jButtonAltaMesaAceptar.setText("Aceptar");
        jButtonAltaMesaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaMesaAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAltaMesaAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLocalizacion)
                            .addComponent(jLabelIdentificador)
                            .addComponent(jLabelCapacidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelAltaMesa)
                            .addComponent(jTextFieldIdentificador)
                            .addComponent(jTextFieldLocalizacion)
                            .addComponent(jTextFieldCapacidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(validationPanelAltaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelAltaMesa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificador)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalizacion)
                    .addComponent(jTextFieldLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacidad)
                    .addComponent(jTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validationPanelAltaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAltaMesaAceptar)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAltaMesaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaMesaAceptarActionPerformed
        // TODO comprobar si la mesa existe antes de añadirla
        /*
        // Necesario para validacion tradicional
        if (validarFormulario()) {
        JOptionPane.showMessageDialog(this, "Formulario correcto");     //aquí llamaríamos a la lógica y haríamos lo que fuese
        setVisible(false);  //supongo que oculta el formulario AltaMesa (preconfigurado al desarrollar el método jButtonAltaMesaAceptarActionPerformed
        }
         */
 /*
        // EJEMPLO PROPIO DI_PI1EVAL (adaptado a errores) + DIEGO
        int idMesa = Integer.parseInt(jTextFieldIdMesa.getText());
        String localizacion = jTextFieldLocalizacion.getText();
        int capacidad = Integer.parseInt(jTextFieldCapacidad.getText());

        Mesa mesa = new Mesa(idMesa, localizacion, capacidad);  // mesa temporal
        // Comprobamos si es un alta o una modificación
        if (mesaModificar == null) {
            if (logicaNegocio.existeMesa(mesa)) {
                JOptionPane.showMessageDialog(this, "La mesa con identificador " + mesa.getIdMesa() + " ya existe.\nPor favor, introduzca otro identificador.", "ERROR ALTA MESA", JOptionPane.ERROR_MESSAGE);
                System.out.println("Mesa NO añadida.");  //comprobación consola
            } else {
                logicaNegocio.altaMesa(mesa);
                //Dialogo éxito alta
                //setVisible(false);    // oculta el formulario (pero no lo destruye)
                dispose();              // destruye el formulario
            }
        } else {
            mesaModificar.setIdMesa(idMesa);
            mesaModificar.setLocalizacion(localizacion);
            mesaModificar.setCapacidad(capacidad);

            logicaNegocio.altaMesa(mesaModificar);
            //Dialogo éxito modificación
            //setVisible(false);    // oculta el formulario (pero no lo destruye)
            dispose();              // destruye el formulario
        }
         */
        int idMesa = Integer.parseInt(jTextFieldIdentificador.getText());
        String localizacion = jTextFieldLocalizacion.getText();
        int capacidad = Integer.parseInt(jTextFieldCapacidad.getText());

        Mesa mesa = new Mesa(idMesa, localizacion, capacidad);      // mesa temporal
        // Comprobamos si es un alta o una modificación
        if (mesaModificar == null) {
            // TODO: Corregir rechazo id duplicado al modificar
            if (logicaNegocio.existeMesa(mesa)) {
                JOptionPane.showMessageDialog(this, "La mesa con identificador " + mesa.getIdMesa() + " ya existe.\nPor favor, introduzca otro identificador.", "ERROR ALTA MESA", JOptionPane.ERROR_MESSAGE);
                System.out.println("Mesa NO añadida.");  //comprobación consola
            } else {
                logicaNegocio.altaMesa(mesa);
                //gestionMesas.anhadirMesa(mesa);   // si utilizamos DefaultTableModel
                // Dialogo éxito alta
                JOptionPane.showMessageDialog(this, "Mesa añadida con éxito.", "ALTA MESA", JOptionPane.INFORMATION_MESSAGE);
                //setVisible(false);    // oculta el formulario (pero no lo destruye)
                dispose();              // destruye el formulario
            }
        } else {
            mesaModificar.setIdMesa(idMesa);
            mesaModificar.setLocalizacion(localizacion);
            mesaModificar.setCapacidad(capacidad);

            logicaNegocio.altaMesa(mesaModificar);
            // Dialogo éxito modificación
            JOptionPane.showMessageDialog(this, "Mesa modificada con éxito.", "MODIFICACIÓN MESA", JOptionPane.INFORMATION_MESSAGE);
            dispose();

            logicaNegocio.listarMesas();  // comprobación consola
        }
    }//GEN-LAST:event_jButtonAltaMesaAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAltaMesaAceptar;
    private javax.swing.JLabel jLabelAltaMesa;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelLocalizacion;
    private javax.swing.JTextField jTextFieldCapacidad;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldLocalizacion;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanelAltaMesa;
    // End of variables declaration//GEN-END:variables
}
