package gui;

import dto.Mesa;
import dto.Ticket;
import java.io.File;
import java.net.URL;
import java.util.Collections;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.MutableComboBoxModel;
import logica.LogicaNegocio;

/**
 *
 * @author sergio
 */
public class FiltradoTicketMesa extends javax.swing.JDialog {

    private PantallaPrincipal pantallaPrincipal;
    private LogicaNegocio logicaNegocio;
    //private Ticket ticketFiltrado;
    private Mesa mesaFiltradoTicket;

    /**
     * Creates new form FiltradoTicketMesa
     */
    public FiltradoTicketMesa(java.awt.Frame parent, boolean modal, LogicaNegocio logicaNegocio) {    // Frame cambiado a Dialog
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;
        this.logicaNegocio = logicaNegocio;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("FILTRADO TICKET POR MESA");
        ponLaAyuda();

        // Cargado listaMesas en ComboBox
        MutableComboBoxModel<Mesa> modelListaMesas = new DefaultComboBoxModel<Mesa>();
        jComboBoxListaMesas.setModel(modelListaMesas);
        // TODO: Probar si funciona quitando parafernalia MutableComboBoxModel (como categorias productos)
        for (Mesa mesa : logicaNegocio.getListaMesas()) {
            jComboBoxListaMesas.addItem(mesa);      // TODO: Mejor con getter IdMesa
        }

        // extraído de https://tips4java.wordpress.com/2013/11/17/combo-box-with-custom-renderer/
        /*// Use the KeySelectionRenderer to determine which property from the Foo object to display in the combo box
        KeySelectionRenderer renderer = new KeySelectionRenderer(jComboBoxListaMesas) {
        @Override
        public String getDisplayValue(Object value) {
        Ticket ticket = (Ticket) value;
        return ticket.getDescription();
        }
        };*/
        // TODO: ¿Validación seleccionado ComboBox? y desbloqueo botón Aceptar
        //jButtonAperturaTicketAceptar.setEnabled(false);        // necesario si hubiese validación
    }

    private void ponLaAyuda() {
        try {
        // Carga el fichero de ayuda
        File fichero = new File("help"+File.separator+"help_set.hs");
        URL hsURL = fichero.toURI().toURL();
        
        HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
        HelpBroker hb = helpset.createHelpBroker();
        
        // Pone ayuda a item de menu al pulsarlo 
        // y a F1 en ventana principal.
        hb.enableHelpOnButton(jMenuItemMostrarAyuda, "filtrado_ticket_mesa", helpset);
        hb.enableHelpKey(getRootPane(), "filtrado_ticket_mesa", helpset);
        } catch (Exception e) {
        e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabelFiltradoTicketMesa = new javax.swing.JLabel();
        jLabelMesa = new javax.swing.JLabel();
        jComboBoxListaMesas = new javax.swing.JComboBox<>();
        jButtonFiltradoTicketMesaAceptar = new javax.swing.JButton();
        jMenuBarFiltradoTicketMesa = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemMostrarAyuda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFiltradoTicketMesa.setText("FILTRADO TICKET POR MESA");

        jLabelMesa.setText("Mesa");

        jButtonFiltradoTicketMesaAceptar.setText("Aceptar");
        jButtonFiltradoTicketMesaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltradoTicketMesaAceptarActionPerformed(evt);
            }
        });

        jMenuAyuda.setText("Ayuda");

        jMenuItemMostrarAyuda.setText("Mostrar ayuda");
        jMenuAyuda.add(jMenuItemMostrarAyuda);

        jMenuBarFiltradoTicketMesa.add(jMenuAyuda);

        setJMenuBar(jMenuBarFiltradoTicketMesa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(jLabelFiltradoTicketMesa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMesa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFiltradoTicketMesaAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jComboBoxListaMesas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelFiltradoTicketMesa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxListaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFiltradoTicketMesaAceptar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltradoTicketMesaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltradoTicketMesaAceptarActionPerformed
        /*
        // TODO: Crear listaTicketsFiltradoMesa y crear método anhadirTicketFiltradoMesa() en LogicaNegocio
        if (ticketFiltrado.getMesaTicket().getIdMesa() == jComboBoxListaMesas.getSelectedItem()){
        logicaNegocio.anhadirTicketFiltradoMesa(ticketFiltrado);
        }
        logicaNegocio.listarTickets();  // comprobación consola
        */
        mesaFiltradoTicket = (Mesa) jComboBoxListaMesas.getSelectedItem();
        logicaNegocio.setMesaFiltradoTicket(mesaFiltradoTicket);
        //logicaNegocio.getListaTicketsFiltradoMesa(mesaFiltradoTicket);
        
        VisualizacionTicketsPorMesa visualizacionTicketsFiltradoMesa = new VisualizacionTicketsPorMesa(this, true, logicaNegocio);    // NOTA: Si necesitase un Frame (pero recibe un Dialog). Se podría
        visualizacionTicketsFiltradoMesa.setVisible(true);                                                                                      // arreglar con con this.pantallaPrincipal (Frame) por this (Dialog)

        dispose();
    }//GEN-LAST:event_jButtonFiltradoTicketMesaAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltradoTicketMesaAceptar;
    private javax.swing.JComboBox<Mesa> jComboBoxListaMesas;
    private javax.swing.JLabel jLabelFiltradoTicketMesa;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBarFiltradoTicketMesa;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemMostrarAyuda;
    // End of variables declaration//GEN-END:variables
}
