package gui;

import dto.Producto;
import dto.ProductoTicket;
import dto.Ticket;
import gui.tablemodels.TableModelProductosTicket;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import logica.LogicaNegocio;

/**
 *
 * @author sergio
 */
public class VisualizacionTicketIndividual extends javax.swing.JDialog {

    // TODO (extra): Eliminar clase o adaptar a su función (ver ticket)
    // Clase duplicada a partir de GestionProductosTicket
    private PantallaPrincipal pantallaPrincipal;
    private LogicaNegocio logicaNegocio;

    // Almacenamos aquí esta propiedad para poder acceder a ella desde el botón
    // de filtrar
    private TableRowSorter<TableModelProductosTicket> sorter;     // TODO: Corregir error selección tras filtrado

    /**
     * Creates new form GestionTicket
     */
    // Será una apertura si el valor de ticketModificar es null 
    // y será una reapertura si tiene un valor
    // Constructor Apertura
    public VisualizacionTicketIndividual(java.awt.Frame parent, boolean modal, LogicaNegocio logicaNegocio) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;     // TODO: En caso de mostrar desde otras pantallas ¿añadirlas al constructor o crear un contructor nuevo por cada vía de acceso?
        this.logicaNegocio = logicaNegocio;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("FORMULARIO APERTURA TICKET");
        rellenarTablaProductosTicket();

        // Recogemos numeroTicket e idMesa
        jLabelNumeroTicket.setText("Nº ticket: " + Integer.toString(logicaNegocio.getCurrentTicket().getNumeroTicket()));
        jLabelIdMesa.setText("Mesa: " + Integer.toString(logicaNegocio.getCurrentTicket().getMesaTicket().getIdMesa()));
        //jTextFieldTotal.setText(Double.toString(currentTicket.calcularTotalTicket()));    // TODO: ¿Por qué no funciona?
        jTextFieldTotal.setText(Double.toString(logicaNegocio.getCurrentTicket().calcularTotalTicket()));       // TODO: Corregir problema redondeo
    }

    // Utilizando un AbstractTableModel
    public void rellenarTablaProductosTicket() {    // NOTA: cambiado a public para poder acceder desde CantidadesProducto
        //TableModelProductosTicket tmpt = new TableModelProductosTicket(logicaNegocio.getListaProductosTicket());
        TableModelProductosTicket tmpt = new TableModelProductosTicket(logicaNegocio.getCurrentTicket().getListaProductosTicket());
        jTableProductosTicket.setModel(tmpt);

        /*
        // TODO: Eliminar si todo funciona correctamente
        // Añadimos la funcionalidad de ordenar
        sorter = new TableRowSorter<>(tmpt);            // TODO: Eliminar para que no de error
        jTableProductosTicket.setRowSorter(sorter);     // al seleccionar un item tras ordenar

        // Establecemos el orden por defecto
        List<SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
         */
    }

    // TODO: Debe permitir tener más de un ticket abierto a la vez (pero solo uno por mesa)
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVisualizacionTicketIndividual = new javax.swing.JLabel();
        jLabelNumeroTicket = new javax.swing.JLabel();
        jLabelIdMesa = new javax.swing.JLabel();
        jButtonVolverAtras = new javax.swing.JButton();
        jScrollPaneProductosTicket = new javax.swing.JScrollPane();
        jTableProductosTicket = new javax.swing.JTable();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonCerrarTicket = new javax.swing.JButton();
        jButtonReaperturaTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelVisualizacionTicketIndividual.setText("VISUALIZACIÓN TICKET");

        jLabelNumeroTicket.setText("IdTicketValue");

        jLabelIdMesa.setText("IdMesaValue");

        jButtonVolverAtras.setText("Volver atrás");
        jButtonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAtrasActionPerformed(evt);
            }
        });

        jTableProductosTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneProductosTicket.setViewportView(jTableProductosTicket);

        jLabelTotal.setText("TOTAL");

        jButtonCerrarTicket.setText("Cerrar ticket");

        jButtonReaperturaTicket.setText("Reapertura ticket");
        jButtonReaperturaTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaperturaTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonVolverAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReaperturaTicket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVisualizacionTicketIndividual)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTotal)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelNumeroTicket)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelIdMesa))
                            .addComponent(jScrollPaneProductosTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonCerrarTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelVisualizacionTicketIndividual)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroTicket)
                    .addComponent(jLabelIdMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButtonReaperturaTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVolverAtras))
                    .addComponent(jScrollPaneProductosTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCerrarTicket)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverAtrasActionPerformed

    private void jButtonReaperturaTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaperturaTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaperturaTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarTicket;
    private javax.swing.JButton jButtonReaperturaTicket;
    private javax.swing.JButton jButtonVolverAtras;
    private javax.swing.JLabel jLabelIdMesa;
    private javax.swing.JLabel jLabelNumeroTicket;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelVisualizacionTicketIndividual;
    private javax.swing.JScrollPane jScrollPaneProductosTicket;
    private javax.swing.JTable jTableProductosTicket;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
