/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author SC
 */
public class AltaCarrera extends javax.swing.JDialog {

    /**
     * Creates new form AltaCarrera
     */
    public AltaCarrera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAltaCarrera = new javax.swing.JLabel();
        jLabelNombreCarrera = new javax.swing.JLabel();
        jLabelFechaCarrera = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelNumMaxParticipantes = new javax.swing.JLabel();
        jLabelListaCorredoresDorsales = new javax.swing.JLabel();
        jTextFieldNombreCarrera = new javax.swing.JTextField();
        jSpinnerFechaCarrera = new javax.swing.JSpinner();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldNumMaxParticipantes = new javax.swing.JTextField();
        jTextFieldListaCorredoresDorsales = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelAltaCarrera.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelAltaCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAltaCarrera.setText("ALTA CARRERA");

        jLabelNombreCarrera.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNombreCarrera.setText("Nombre de la carrera");

        jLabelFechaCarrera.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFechaCarrera.setText("Fecha de la carrera");

        jLabelLugar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelLugar.setText("Lugar de la carrera");

        jLabelNumMaxParticipantes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNumMaxParticipantes.setText("Número máximo de participantes");

        jLabelListaCorredoresDorsales.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelListaCorredoresDorsales.setText("Lista de corredores y dorsales");

        jSpinnerFechaCarrera.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAltaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLugar)
                    .addComponent(jLabelFechaCarrera)
                    .addComponent(jLabelNombreCarrera)
                    .addComponent(jLabelListaCorredoresDorsales)
                    .addComponent(jLabelNumMaxParticipantes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldListaCorredoresDorsales, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jTextFieldLugar)
                    .addComponent(jTextFieldNombreCarrera)
                    .addComponent(jTextFieldNumMaxParticipantes)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelAltaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreCarrera)
                    .addComponent(jTextFieldNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLugar)
                            .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumMaxParticipantes)
                            .addComponent(jTextFieldNumMaxParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelListaCorredoresDorsales))
                    .addComponent(jTextFieldListaCorredoresDorsales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAltaCarrera;
    private javax.swing.JLabel jLabelFechaCarrera;
    private javax.swing.JLabel jLabelListaCorredoresDorsales;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelNombreCarrera;
    private javax.swing.JLabel jLabelNumMaxParticipantes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaCarrera;
    private javax.swing.JTextField jTextFieldListaCorredoresDorsales;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldNombreCarrera;
    private javax.swing.JTextField jTextFieldNumMaxParticipantes;
    // End of variables declaration//GEN-END:variables
}
