/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dto.Carrera;
import dto.Corredor;
import interfaztablemodels.TableModelCarreras;
import interfaztablemodels.TableModelCorredores;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.GestorFichero;
import logica.LogicaNegocio;
import static utils.Utils.sdf;

/**
 *
 * @author SC
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static final String RUTA_LOGO = "/imgs/240x320-exercise_sport_13306.png";
    private LogicaNegocio logicaNegocio = new LogicaNegocio();
    GestorFichero gf = new GestorFichero(logicaNegocio);

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        rellenarTablaCorredores();
        rellenarTablaCarreras();

        //Establecer una imagen en una label
        jLabelIcono.setIcon(new ImageIcon(getClass().getResource(RUTA_LOGO)));
        //Establecer el logo del a aplicación
        setIconImage(new ImageIcon(getClass().getResource(RUTA_LOGO)).getImage());
        //Establecer el título de la aplicación
        setTitle("Gestión de carreras");

    }

    public void rellenarTablaCorredores() {
        String[] columnas = {"Nombre", "DNI", "Fecha de nacimiento", "Dirección", "Teléfono de contacto"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for (Corredor corredor : logicaNegocio.getListaCorredores()) {
            String[] c = new String[5];
            c[0] = corredor.getNombre();
            c[1] = corredor.getDni();
            c[2] = sdf.format(corredor.getFechaNacimiento());
            c[3] = corredor.getDireccion();
            c[4] = String.valueOf(corredor.getTelefonoContacto());
            dtm.addRow(c);
        }
        jTableCorredores.setModel(dtm);

    }

    //Utilizando un AbstractTableModel
    private void rellenarTablaCorredores2() {
        jTableCorredores.setModel(new TableModelCorredores(logicaNegocio.getListaCorredores()));
    }

    public void rellenarTablaCarreras() {
        TableModelCarreras tmc = new TableModelCarreras(logicaNegocio.getListaCarreras());
        jTableCarreras.setModel(tmc);
    }

    /*public void rellenarTablaCarreras() {
        String[] columnas = {"Nombre", "Fecha", "Lugar", "Nº máximo de participantes"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for (Carrera carrera : logicaNegocio.getListaCarreras()) {
            String[] r = new String[4];
            r[0] = carrera.getNombreCarrera();
            r[1] = carrera.getFechaCarrera();
            r[2] = carrera.getLugar();
            r[3] = carrera.getNumMaxParticipantes();
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        jButtonAnhadirCorredor = new javax.swing.JButton();
        jScrollPaneCorredor = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jButtonModificarCorredor = new javax.swing.JButton();
        jButtonBorrarCorredor = new javax.swing.JButton();
        jLabelIcono = new javax.swing.JLabel();
        jScrollPaneCarreras = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonAnhadirCarrera = new javax.swing.JButton();
        jButtonModificarCarrera = new javax.swing.JButton();
        jButtonBorrarCarrera = new javax.swing.JButton();
        jButtonConfiguracion = new javax.swing.JButton();
        jButtonAnhadirCorredorACarrera = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAnhadirCorredor.setText("AÑADIR");
        jButtonAnhadirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirCorredorActionPerformed(evt);
            }
        });

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCorredor.setViewportView(jTableCorredores);

        jButtonModificarCorredor.setText("MODIFICAR");
        jButtonModificarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCorredorActionPerformed(evt);
            }
        });

        jButtonBorrarCorredor.setText("BORRAR");
        jButtonBorrarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCorredorActionPerformed(evt);
            }
        });

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneCarreras.setViewportView(jTableCarreras);

        jButtonAnhadirCarrera.setText("AÑADIR");
        jButtonAnhadirCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirCarreraActionPerformed(evt);
            }
        });

        jButtonModificarCarrera.setText("MODIFICAR");
        jButtonModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCarreraActionPerformed(evt);
            }
        });

        jButtonBorrarCarrera.setText("BORRAR");

        jButtonConfiguracion.setText("CONFIGURACIÓN");
        jButtonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfiguracionActionPerformed(evt);
            }
        });

        jButtonAnhadirCorredorACarrera.setText("AÑADIR CORREDOR A CARRERA");
        jButtonAnhadirCorredorACarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnhadirCorredorACarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneCorredor)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButtonAnhadirCorredor)
                                .addGap(80, 80, 80)
                                .addComponent(jButtonModificarCorredor)
                                .addGap(80, 80, 80)
                                .addComponent(jButtonBorrarCorredor))
                            .addComponent(jScrollPaneCarreras)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButtonConfiguracion)
                        .addGap(197, 197, 197)
                        .addComponent(jButtonAnhadirCarrera)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonModificarCarrera)
                        .addGap(80, 80, 80)
                        .addComponent(jButtonBorrarCarrera)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAnhadirCorredorACarrera)
                .addGap(286, 286, 286))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPaneCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAnhadirCorredor)
                            .addComponent(jButtonModificarCorredor)
                            .addComponent(jButtonBorrarCorredor))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabelIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAnhadirCarrera)
                        .addComponent(jButtonConfiguracion))
                    .addComponent(jButtonBorrarCarrera)
                    .addComponent(jButtonModificarCarrera))
                .addGap(54, 54, 54)
                .addComponent(jButtonAnhadirCorredorACarrera)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnhadirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirCorredorActionPerformed
        AltaCorredor pantallaAltaCorredor = new AltaCorredor(this, true, logicaNegocio);
        pantallaAltaCorredor.setLocationRelativeTo(null);
        pantallaAltaCorredor.setVisible(true);
        // El hilo se queda bloqueado en el setVisible porque el dialogo es modal.
        rellenarTablaCorredores();
        //Diálogo para mostrar mensaje de confirmación al añadir corredor.
        JOptionPane.showMessageDialog(this, "Corredor añadido con éxito", "Alta Corredor", JOptionPane.INFORMATION_MESSAGE);
        //Creación del CSV
        gf.escribirArchivo();
        //Lee el List con la nueva información (corredores añadidos)
        gf.leerArchivo();
        logicaNegocio.listarCorredores();
    }//GEN-LAST:event_jButtonAnhadirCorredorActionPerformed

    private void jButtonModificarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCorredorActionPerformed
        int seleccionado = jTableCorredores.getSelectedRow();
        Corredor corredorSeleccionado = logicaNegocio.getListaCorredores().get(seleccionado);//getTablaCorredores().get(seleccionado);
        AltaCorredor dialogoModificar = new AltaCorredor(this, true, corredorSeleccionado);
        dialogoModificar.setLocationRelativeTo(null);
        dialogoModificar.setVisible(true);
        //El hilo se queda bloqueado en el setVisible porque el dialogo es modal.
        rellenarTablaCorredores();
        //Diálogo para mostrar mensaje de confirmación al añadir corredor.
        JOptionPane.showMessageDialog(this, "Corredor modificado con éxito", "Modificación Corredor", JOptionPane.INFORMATION_MESSAGE);
        //Creación del CSV
        gf.escribirArchivo();
        //Lee el List con la nueva información (corredores añadidos)
        gf.leerArchivo();
        logicaNegocio.listarCorredores();
    }//GEN-LAST:event_jButtonModificarCorredorActionPerformed

    private void jButtonBorrarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCorredorActionPerformed
        int seleccionado = jTableCorredores.getSelectedRow();
        //Corredor corredorSeleccionado = logicaNegocio.getListaCorredores().get(seleccionado);
        //continuar aquí---------------
        //listaCorredores.remove(seleccionado);
        logicaNegocio.getListaCorredores().remove(seleccionado);

    }//GEN-LAST:event_jButtonBorrarCorredorActionPerformed

    private void jButtonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfiguracionActionPerformed
        Configuracion pantallaConfiguracion = new Configuracion(this, true);
        pantallaConfiguracion.setLocationRelativeTo(null);
        pantallaConfiguracion.setVisible(true);

    }//GEN-LAST:event_jButtonConfiguracionActionPerformed

    private void jButtonAnhadirCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirCarreraActionPerformed
        AltaCarrera pantallaAltaCarrera = new AltaCarrera(this, true, logicaNegocio);
        pantallaAltaCarrera.setLocationRelativeTo(null);
        pantallaAltaCarrera.setVisible(true);
        // El hilo se queda bloqueado en el setVisible porque el dialogo es modal.
        // Necesario para que no se rellenase la tabla hasta que se cierre la ventana de alta (setVisible(false))
        rellenarTablaCarreras();

    }//GEN-LAST:event_jButtonAnhadirCarreraActionPerformed

    private void jButtonModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCarreraActionPerformed
        int seleccionado = jTableCarreras.getSelectedRow();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar alguna carrera", "Advertencia modificación carrera", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Carrera carreraSeleccionada = logicaNegocio.getListaCarreras().get(seleccionado);
            AltaCarrera pantallaAltaCarrera = new AltaCarrera(this, true, carreraSeleccionada);
            pantallaAltaCarrera.setLocationRelativeTo(null);
            pantallaAltaCarrera.setVisible(true);
            rellenarTablaCarreras();
        }
    }//GEN-LAST:event_jButtonModificarCarreraActionPerformed

    private void jButtonAnhadirCorredorACarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnhadirCorredorACarreraActionPerformed
        int corredorSeleccionado = jTableCorredores.getSelectedRow();
        Corredor c = logicaNegocio.getListaCorredores().get(corredorSeleccionado);
        int carreraSeleccionada = jTableCarreras.getSelectedRow();
        Carrera r = logicaNegocio.getListaCarreras().get(carreraSeleccionada);
        int contPlazasLibres;
        for (int i = 0; i < r.getNumMaxParticipantes(); i++) {
            if (r.getListaCorredoresInscritos()[i] == null) {
                r.getListaCorredoresInscritos()[i] = c;
                break;
                
            }
        }
        for (Corredor unCorredor : r.getListaCorredoresInscritos()) {
            System.out.println(unCorredor.toString());
        }
        
        rellenarTablaCarreras();
    }//GEN-LAST:event_jButtonAnhadirCorredorACarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Versión española (ponerla siempre), aunque en este caso esta librería no está traducida
                Locale.setDefault(new Locale("es", "ES"));
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnhadirCarrera;
    private javax.swing.JButton jButtonAnhadirCorredor;
    private javax.swing.JButton jButtonAnhadirCorredorACarrera;
    private javax.swing.JButton jButtonBorrarCarrera;
    private javax.swing.JButton jButtonBorrarCorredor;
    private javax.swing.JButton jButtonConfiguracion;
    private javax.swing.JButton jButtonModificarCarrera;
    private javax.swing.JButton jButtonModificarCorredor;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JScrollPane jScrollPaneCarreras;
    private javax.swing.JScrollPane jScrollPaneCorredor;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTable jTableCorredores;
    // End of variables declaration//GEN-END:variables
}
