/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import logica.Usuario;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import logica.Tweet;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author sergio
 */
public class Principal extends javax.swing.JFrame {

    List<Tweet> listaTweetsUsuario1;
    List<Tweet> listaTweetsUsuario2;

    //Usuario usuario1 = new Usuario ("Mariano Rajoy", listaTweetsUsuario1);
    //Usuario usuario2 = new Usuario ("José María Aznar", listaTweetsUsuario2);
    List<Usuario> listaUsuarios;

    // Método para rellenar las listas de prueba
    private void rellenarPrueba() {

        listaTweetsUsuario1 = new ArrayList<>();
        listaTweetsUsuario1.add(new Tweet("A veces la mejor decisión es no tomar ninguna decisión, que también es tomar una decisión."));
        listaTweetsUsuario1.add(new Tweet("Como decía Galileo, el movimiento siempre se acelera cuando se va a detener."));
        listaTweetsUsuario1.add(new Tweet("Cuanto peor mejor para todos y cuanto peor para todos mejor, mejor para mí el suyo, beneficio político."));
        listaTweetsUsuario1.add(new Tweet("Es el vecino el que elige al alcalde y es el alcalde el que quiere que sean los vecinos el alcalde."));
        listaTweetsUsuario1.add(new Tweet("España es un gran país que hace cosas importantes y tiene españoles."));

        listaTweetsUsuario2 = new ArrayList<>();
        listaTweetsUsuario2.add(new Tweet("España va bien."));
        listaTweetsUsuario2.add(new Tweet("¡Váyase señor González, váyase!"));
        listaTweetsUsuario2.add(new Tweet("Yo también hablo catalán en la intimidad."));
        listaTweetsUsuario2.add(new Tweet("A mí no me gusta que me digan: no puede ir usted a más de tanta velocidad, no puede usted comer hamburguesas de tanto, debe usted evitar esto y además a usted le prohíbo beber vino."));
        listaTweetsUsuario2.add(new Tweet("O gobierna el PP o habrá un riesgo real para el futuro de España con una coalición de pancarteros, comunistas e independentistas que todas las mañanas desayunan galletas de rencor y de odio y quieren romper España."));
        
        Usuario usuario1 = new Usuario("Mariano Rajoy", listaTweetsUsuario1);
        Usuario usuario2 = new Usuario("José María Aznar", listaTweetsUsuario2);

        //usuario1.setListaTweets(listaTweetsUsuario1);
        //usuario2.setListaTweets(listaTweetsUsuario2);
        listaUsuarios = new ArrayList<>();
        listaUsuarios.add(usuario1);
        listaUsuarios.add(usuario2);
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        rellenarPrueba();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuarioActionPerformed(evt);
            }
        });

        jLabelNombreUsuario.setText("Nombre usuario:");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuarioActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            String nombreUsuarioTextField = jTextFieldNombreUsuario.getText();  // Sustituir por Scanner.nextLine();
            int indice = -1;
            for (Iterator<Usuario> it = listaUsuarios.iterator(); it.hasNext();) {
                Usuario usuario = it.next();
                if (usuario.getNameUser().equalsIgnoreCase(nombreUsuarioTextField)) {
                    indice = listaUsuarios.indexOf(usuario);
                    break;
                }
            }
            List<Tweet> listaTweetsUsuario = listaUsuarios.get(indice).getListaTweets();     // Fallaba al coger la listaTweets asociada al usuario
            //La encapsulamos en el objeto adecuado
            JRDataSource dataSource = new JRBeanCollectionDataSource(listaTweetsUsuario);
            //Creamos el map para los parámetros
            Map parametros = new HashMap();
            parametros.put("NOMBRE_USUARIO", nombreUsuarioTextField);       // Si no metemos esta línea el map va sin parametros (vacío)
            JasperPrint print = JasperFillManager.fillReport("informes/prueba_informe_twitter.jasper", parametros, dataSource);
            JasperExportManager.exportReportToPdfFile(print, "informes/prueba_informe_twitter_gui.pdf");
            //JOptionPane.showMessageDialog(this, listaUsuarios.get(indice).getListaTweets().size());     // Muestra el nº de tweets (tb. controla que se haya hecho bien)
        } catch (Throwable e) {
            e.printStackTrace();
        }
        //this.dispose();       // ¿Debería cerrar JFrame (parece que centra JOptionPane)? Queda en ejecución hasta detenerla manualmente
        JOptionPane.showMessageDialog(this, "El informe ha sido generado satisfactoriamente.", "Informe Twitter", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
